### ISSUE TITLE
BaseQuantities NetVolume and NetSideArea

### ISSUE THREAD

**Issue by MagneGanz** [Autodesk/revit-ifc#198]
Looks like a Type-error somewhere in the Code. 
NetSideArea and NetVolume are listed Twice with different values. 
The large values should have been sorted under GrossSideAre and GrossVolume.

Hope you can fix this.
![BaseQuantities](https://user-images.githubusercontent.com/42205542/83138652-64f8b100-a0eb-11ea-9318-9dd23105e7f2.PNG)

**Comment by AngelVelezSosa** [comment]
I'll file an internal issue to review this.

**Comment by AngelVelezSosa** [comment]
@MagneGanz : can you check this again with the newest version?  My internal testing implies that it has been fixed, but if you can repro it, it would be great to have a tiny test file.

**Comment by MagneGanz** [comment]
@AngelVelezSosa : Thanks! The Net and Gross looks sorted. There might be something with the units on the GrossVolume?

![GrossVolume](https://user-images.githubusercontent.com/42205542/90221621-d30b6500-de0a-11ea-81de-f6990b193d23.PNG)

![IFC Gross vs Net](https://user-images.githubusercontent.com/42205542/90221261-2fba5000-de0a-11ea-8504-e6abd2d913ed.PNG)

[Project1.zip](https://github.com/Autodesk/revit-ifc/files/5072999/Project1.zip)

**Comment by AngelVelezSosa** [comment]
If the length unit is in millimeters, that's something that has been addressed recently and is open source update compatible, so hopefully should make an update in the near future.  Will verify with your model.

**Comment by parrela** [comment]
It looks OK to me in the latest builds, using mm units or imperial. could you send that actual .rvt so I can be totally sure? THanks.
Andy

**Comment by StewartGH1970** [comment]
@AngelVelezSosa i had never noticed this issue before but i have just seen this is still a problem in Revit 2020 but seems to have been addressed in Revit 2021
can you let me know if Revit 2020 will be getting an update to address this double export of NetSideArea as i have a project where ifc is being used and the QS software is reporting errors because of this.

**Comment by AngelVelezSosa** [comment]
We intend to also update Revit 2020 and 2019 to the certified version, which presumably would include this fix.

**Comment by StewartGH1970** [comment]
if the update doesn't include a fix then doesn't really address this issue? 

can you let us know if you intend to address the 2020 issue?

**Comment by AngelVelezSosa** [comment]
Let me be more clear. We are in the process of updating Revit 2021 to the certified version of IFC.  Next, we intend to update Revit 2020/2019.  I can't promise that those versions will fix this issue, because I don't know the details of what can be definitely backsubmitted.  But the intention is to bring the fix from 2021 back to 2020 and 2019.  We will have to double check this at that point.

**Comment by StewartGH1970** [comment]
ok thanks @AngelVelezSosa keep up the great work
