### ISSUE TITLE
PR: Displaced doors/windows in slightly-off-axis-walls

### ISSUE THREAD

**Issue by andydandy74** [Autodesk/revit-ifc#884]
### Problem Description

This one's something that we recently experienced on a refurbishment project:
- Windows and doors hosted in slightly-off-axis-walls get displaced when their opening is generated via a **void cut**. 
- The displacement increases with growing distance from the internal origin. 
- Doors/windows that use the wall opening tool for creating their openings are **not** affected.
- Doors/windows hosted in walls that are more than slightly off angle (e.g. 0.5°) are **not** affected.

<img width="985" height="787" alt="Image" src="https://github.com/user-attachments/assets/0bfdb2ae-3f3e-4959-98b9-f351f1a125fc" />

### Revit Version

2025.4.x

### IFC for Revit Addon Version

25.4.0

### Windows Version

11 24H2

**Comment by ArtemHnatko** [comment]
Hello @andydandy74, 

Thank you for providing a detailed problem description and a sample model. We have conducted an investigation and successfully reproduced the bug with Revit 2025.4.x using your sample file.

Our testing confirms that this specific issue is not present in Revit 2026.x. The problem appears to have been addressed and fixed in the Revit 2026 release.

**Testing environment:**
- Autodesk Revit 2025 (IFC 25.4.0.27)
- Autodesk Revit 2026 (IFC 26.2.0.0)

<img width="964" height="2759" alt="Image" src="https://github.com/user-attachments/assets/d11a162c-9167-4048-9ec6-f5118a4c3f8a" />

**Comment by ArtemHnatko** [comment]
This issue is also reported in Jira as "REVIT-240077" and is currently in the "Open" status.

**Comment by ls00350** [comment]
Still a problem in R2024 using ifc exporter version 24.3.40.0. On windows with openings made using voids the opening comes out correctly but window geometry is thrown off the opening along the wall length in walls that are "slightly off axis". I haven't tested if there's a problem with other object classes as well.
